name: Deploy to GitHub Pages
 
on:
  push:
    branches: [ "main" ]  # Se ejecuta al hacer push a 'main'
 
jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Descarga el código
 
      - name: Setup Pages
        uses: actions/configure-pages@v3
 
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'  # Usa los archivos en la raíz
 
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
